import React from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";

const array = [1, 4, 5, 13, 34, 23, 2, 5, 8, 9, 10];

export default function Home() {
  const bubbleSort = (arr: number[]) => {
    for (let i = 0; i < arr.length; i++) {
      for (let j = 0; j < arr.length - 1; j++) {
        if (arr[j] < arr[j + 1]) {
          let temp = arr[j];
          arr[j] = arr[j + 1];
          arr[j + 1] = temp;
        }
      }
    }
    return arr;
  };

  return (
    <>
      <Head>
        <title>Bubble</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Bubble</p>
        <canvas></canvas>
      </main>
    </>
  );
}
